### ISSUE TITLE
Question about Score

### ISSUE THREAD

**Issue by stanfordbinet** [joshuous/JankBenchX-Web#1]
Hello!

According to the FAQ _"Score: lower is better"_, yet similar seeming results score **completely** (sic) different - is this a bug, or are we overlooking something/or not being bright enough to correctly interpret/calculate the data?

Example: (Shadow Grid Fling):

https://jankbenchx.now.sh/results/267266490112147976

https://jankbenchx.now.sh/results/267259408453468680

Thanks in advance for any input!

Greetings

**Comment by joshuous** [comment]
Hi, it is not a bug. The formula for score is as follows:

**Score** = mean duration of bad frames (ms) * standard deviation of bad frames * percentage of janks

Reference: https://jankbenchx.now.sh/faq
